version: "3.8"

x-backend: &backend
  build:
    dockerfile: docker/Dockerfile
  environment:
    DEBUG: 0
    DATABASE_HOST: postgres
    CELERY_BROKER_URL: redis://redis:6379/0
    CELERY_RESULT_BACKEND: redis://redis:6379/0
    CACHE_LOCATION: redis://redis:6379
  volumes:
    - ../media_volume:/app/static_cdn/media_root
  restart: unless-stopped
  networks:
    - otagh_tala_backend_network

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - otagh_tala_backend_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - otagh_tala_backend_network

  web:
    <<: *backend
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  celery:
    <<: *backend
    command: celery -A huda worker --loglevel=info
    depends_on:
      - postgres
      - redis

  celery_beat:
    <<: *backend
    command: celery -A huda beat --loglevel=info
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:

networks:
  otagh_tala_backend_network:
    driver: bridge